### ISSUE TITLE
How to combine fromQuery and onDupUpdate?

### ISSUE THREAD

**Issue by zippeurfou** [hiddentao/squel#184]
What I am trying to achieve:

```
INSERT INTO count (object_id, count_type_id, timestamp_start, timestamp_end, value) (SELECT "1" AS "site_id", "2" AS "count_type_site", timestamp_start, timestamp_end, SUM(value) AS "numb" FROM count WHERE (count_type_id =3) AND (object_id IN (SELECT ucid FROM links WHERE (site_id =538) AND (link_type=2))) GROUP BY timestamp_start, timestamp_end) ON DUPLICATE KEY update value=VALUES(value)
```

Here is my code:

```
   var site_id=1;
   var count_type_site=2;
   var count_type_ucid=3;
  var squelMysql = squel.useFlavour('mysql');
  var sql = squelMysql.insert()
                .into("count")
                .fromQuery(["object_id", "count_type_id", "timestamp_start", "timestamp_end", "value"],
                    squel.select()
                    .from("count")
                    .field('"'+site_id+'"', "site_id")
                    .field('"'+count_type_site+'"', "count_type_site")
                    .field("timestamp_start")
                    .field("timestamp_end")
                    .field("SUM(value)", "numb")
                    .where("count_type_id =?", count_type_ucid)
                    .where("object_id IN ?", squel.select().from("links").field("ucid").where("site_id =?", site_id).where("link_type=?", 2))
                    .group("timestamp_start")
                    .group("timestamp_end"))
                    .onDupUpdate('value', 'VALUES(value)', {
                        dontQuote: true
                    })
                .toString();

```

The error is this:

```
Unhandled rejection Error: must be a nestable query, e.g. SELECT
    at InsertFieldsFromQueryBlock.cls.BaseBuilder.BaseBuilder._sanitizeNestableQuery (/Users/marc/Projects/geordi/node_modules/squel/squel.js:205:15)
    at InsertFieldsFromQueryBlock._sanitizeNestableQuery (/Users/marc/Projects/geordi/node_modules/squel/squel.js:31:61)
    at InsertFieldsFromQueryBlock.cls.InsertFieldsFromQueryBlock.InsertFieldsFromQueryBlock.fromQuery (/Users/marc/Projects/geordi/node_modules/squel/squel.js:1230:35)
    at Insert._this.(anonymous function) [as fromQuery] (/Users/marc/Projects/geordi/node_modules/squel/squel.js:1908:20)
    at /Users/marc/Projects/geordi/util/accountingCollect.js:191:18
    at arrayEach (/Users/marc/Projects/geordi/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/marc/Projects/geordi/node_modules/lodash/index.js:3345:13)
    at /Users/marc/Projects/geordi/util/accountingCollect.js:188:11
    at eval (eval at <anonymous> (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/join.js:23:16), <anonymous>:6:20)
    at tryCatcher (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/util.js:26:23)
    at Holder.checkFulfillment (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/join.js:51:40)
    at Promise.eval (eval at <anonymous> (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/join.js:13:16), <anonymous>:6:20)
    at Promise._settlePromiseAt (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/marc/Projects/geordi/node_modules/bluebird/js/main/async.js:133:10)
```

How do I actually combine fromQuery and onDupUpdate?

Thanks for the help.

**Comment by FerrielMelarpis** [comment]
Try: 
```js
var site_id=1;
var count_type_site=2;
var count_type_ucid=3;
var squelMysql = squel.useFlavour('mysql');
var sql = squelMysql.insert()
    .into("count")
    .fromQuery(["object_id", "count_type_id", "timestamp_start", "timestamp_end", "value"],
                squel.select()
                    .from("count")
                    .field('"'+site_id+'"', "site_id")
                    .field('"'+count_type_site+'"', "count_type_site")
                    .field("timestamp_start")
                    .field("timestamp_end")
                    .field("SUM(value)", "numb")
                    .where("count_type_id =?", count_type_ucid)
                    .where("object_id IN ?", squel.select().from("links").field("ucid").where("site_id =?", site_id).where("link_type=?", 2))
                    .group("timestamp_start")
                    .group("timestamp_end"))
    .onDupUpdate('value', 'VALUES(value)', { dontQuote: true })
    .toString();

**Comment by hiddentao** [comment]
Thanks @FerrielMelarpis
