### ISSUE TITLE
update with join

### ISSUE THREAD

**Issue by zippeurfou** [hiddentao/squel#195]
this code does not work:
```
 var query = squel.update()
        .table("links", "l")
        .join("sites", "s", "s.id=l.site_id")
        .set("l.client_id=s.client_id")
        .where("l.client_id=?", squel.select().field("id").from("client").where("tag=?", "OTHR"))
        .where("l.saved_date> ( NOW() - INTERVAL 33 DAY)")
        .toString();

```
throws this error:

```
 .join("sites","s","s.id=l.site_id")
     ^

TypeError: squel.update(...).table(...).join is not a function
    at _updateLinksClient (/Users/marc/Projects/geordi/util/accountingSend.js:386:6)
    at getAccountings (/Users/marc/Projects/geordi/util/accountingSend.js:24:5)
    at Object.<anonymous> (/Users/marc/Projects/geordi/util/accountingSend.js:395:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

However, this mysql query is correct:

```
UPDATE links as l inner join sites as s on s.id=l.site_id SET l.client_id=s.client_id WHERE ( l.client_id=(SELECT id from client where tag="OTHR") ) AND ( l.saved_date > ( NOW() - INTERVAL 33 DAY ) )

```

Am I doing something wrong?

**Comment by abgivant** [comment]
Last I checked, this is not something that is supported, though I think it should be, but you can work around it by adding a custom query.

I have done this by adding a separate `updateJoin` method, but you could probably also overwrite the built-in `update` if you wanted. I am also missing some of the blocks (group, limit, offset, etc.), but they are easy to add.

``` javascript
// Create an update-join method for squel
squel.updateJoin = function(options) {
    return squel.update(options, [
        new squel.cls.StringBlock(options, 'UPDATE'),
        new squel.cls.UpdateTableBlock(options),
        new squel.cls.JoinBlock(options),
        new squel.cls.SetFieldBlock(options),
        new squel.cls.WhereBlock(options)
    ]);
};
```

**Comment by hiddentao** [comment]
I think perhaps this can be added to the mysql flavour.

**Comment by abgivant** [comment]
It would be great if this was added to the core! But the ability to do joins in an update statement is not MySQL-specific. I know you can do it in MSSQL as well, though the syntax varies slightly.

This StackOverflow post includes some of the variations on syntax between different DBs:
http://stackoverflow.com/questions/1293330/how-can-i-do-an-update-statement-with-join-in-sql
