### ISSUE TITLE
Symbol is not defined 

### ISSUE THREAD

**Issue by estvmachine** [hiddentao/squel#256]
Hi, im ussing squel 5.3.3 in Ionic , works in Browser but in a phone make this error:

![image](https://cloud.githubusercontent.com/assets/2062668/16923647/a8c47cae-4cf1-11e6-8be4-e34484b11e82.png)

**Comment by hiddentao** [comment]
What actual error message do you get with 4.4.1?

**Comment by seralf** [comment]
Hi

I'm having a similar problem using explorer, while on chrome everything works fine.

On explorer the problem was:

```
HTML1300: È stata eseguita la navigazione.
ex_squel.html
SCRIPT5009: 'Symbol' non è definito
squel.min.js (1,2447)
jQuery.Deferred exception: 'squel' non è definito ReferenceError: 'squel' non è definito
   at Anonymous function (http://localhost:8080/ex_squel.html:14:3)
   at mightThrow (http://localhost:8080/bower_components/jquery/dist/jquery.js:3508:10)
   at Anonymous function (http://localhost:8080/bower_components/jquery/dist/jquery.js:3576:12) undefined
SCRIPT5009: 'squel' non è definito
jquery.js (3793,3)
```

The code of the page used for manual testing is:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>testing squel.js</title>

<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="bower_components/squel/dist/squel.min.js"></script>

<script type="text/javascript">
	$(function() {
		var sql = squel.select().from('example_table');
		console.log(sql);
	});
</script>

</head>
</html>
```

where I'm using the latest libraries versions, gathered from bower:

```
bower install jquery
bower install squel
```

**Comment by hiddentao** [comment]
What version of IE are you using?

**Comment by seralf** [comment]
Hi

I'm having issues over Exporer 11 (11.212...), while on the latest Chrome (still on win 10) it works correctly

**Comment by hiddentao** [comment]
Hmm this is clearly due to a lack of support for the Babel translation of the `for-of` iterator, which uses Symbols. Perhaps I can rewrite these loops.

**Comment by hiddentao** [comment]
Yep, IE doesn't support it -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator

**Comment by hiddentao** [comment]
Edge does support it, but not Android browsers -> https://kangax.github.io/compat-table/es6/

**Comment by hiddentao** [comment]
The strange thing is that squel.js actually shims Symbol at the top.

**Comment by vigyanhoon** [comment]
Hi,

Getting the same issue in Android 5.0. Can you please inform the fix, or which line causes the issue in squel.js?

Thank you.

**Comment by allthesignals** [comment]
This also isn't supported in Safari

**Comment by allthesignals** [comment]
I'm still seeing this issue on a number of browsers. What do you think the issue is? I will dig some more. Thanks!

**Comment by allthesignals** [comment]
I found this helpful: http://stackoverflow.com/a/33831169/2805018

`<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>`

**Comment by hiddentao** [comment]
Thanks @allthesignals
